name       : python-textdistance
version    : 4.2.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/t/textdistance/textdistance-4.2.1.tar.gz : 46f8df3b26c7f319ab500b417047f61b85c2dd221781cb02f6c9136e5f1c9284
homepage   : https://github.com/life4/textdistance
license    : MIT
component  : programming.python
summary    :  A python library for comparing distance between two or more sequences by many algorithms
description: |
    TextDistance is a python library for comparing distance between two or more sequences by many algorithms. 30+ algorithms, pure python implementation, common interface, optional external libs usage.
build      : |
    %python3_setup
install    : |
    %python3_install
