name       : python-textdistance
version    : 4.5.0
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/t/textdistance/textdistance-4.5.0.tar.gz : 364d43f4f6635742662e3e6cf5372a86859416c84a3c9b2ef9d66d44f5a4385c
homepage   : https://github.com/life4/textdistance
license    : MIT
component  : programming.python
summary    : A python library for comparing distance between two or more sequences by many algorithms
description: |
    TextDistance is a python library for comparing distance between two or more sequences by many algorithms. 30+ algorithms, pure python implementation, common interface, optional external libs usage.
build      : |
    %python3_setup
install    : |
    %python3_install
